---
- name: Install Composer
  get_url:
    url: "https://getcomposer.org/composer.phar"
    dest: /usr/local/bin/composer
    mode: 0755

- name: Composer self update
  command: composer self-update
  register: composer_update_result
  changed_when: composer_update_result | success and 'already using composer version' not in composer_update_result.stderr

- name: Composer config github-oauth
  command: composer config -g github-oauth.github.com {{ composer_github_oauth_token }}
  when: composer_github_oauth_token is defined
